import {readFileSync,writeFileSync,readdirSync,mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
export const root=fileURLToPath(new URL('../../',import.meta.url));
export const library=path.join(root,'exercise-library');
const read=p=>JSON.parse(readFileSync(p,'utf8'));
export function nativeCatalog(){
  const source=readFileSync(path.join(root,'app/src/main/java/com/fit50/app/WorkoutPlanEngine.kt'),'utf8');
  return [...source.matchAll(/Ex\("([^"]+)","([^"]+)","([^"]+)","([^"]+)"([^\n]+)/g)].map(m=>({
    id:m[1],name:m[2],muscle:m[3],type:m[4],phase:m[5].match(/phase="([^"]+)"/)?.[1]||'main',
    difficulty:Number(m[5].match(/difficulty=(\d+)/)?.[1]||1),
    safety:m[5].match(/safety="([^"]+)"/)?.[1]||'',
  }));
}
export function entries(){return readdirSync(path.join(library,'exercises')).filter(f=>f.endsWith('.json')).sort().map(f=>read(path.join(library,'exercises',f)));}
export function validate(all,active){
  const bases=new Map(nativeCatalog().map(e=>[e.id,e])),ids=new Set(),names=new Set();
  for(const e of all){
    if(!/^[a-z][a-z0-9_]{2,63}$/.test(e.id)||ids.has(e.id))throw Error('Invalid or duplicate exercise ID: '+e.id);
    if(typeof e.name!=='string'||!e.name.trim()||names.has(e.name))throw Error('Missing or duplicate name: '+e.id);
    if(!bases.has(e.motion?.id)||!(e.motion.speed>=.4&&e.motion.speed<=1.5))throw Error('Unknown motion or invalid speed: '+e.id);
    if(bases.has(e.id)&&(e.motion.id!==e.id||e.motion.speed!==1))throw Error('Base exercise cannot be replaced: '+e.id);
    if(!['base','tempo-variant'].includes(e.kind))throw Error('Unknown exercise kind: '+e.id);
    if((e.kind==='base')!==bases.has(e.id))throw Error('Incorrect exercise kind: '+e.id);
    ids.add(e.id);names.add(e.name);
  }
  for(const id of bases.keys())if(!ids.has(id))throw Error('Missing base exercise: '+id);
  if(!Array.isArray(active)||new Set(active).size!==active.length)throw Error('Invalid active list');
  for(const id of active)if(!ids.has(id)||bases.has(id))throw Error('Invalid additional exercise: '+id);
  return bases;
}
export function state(){const all=entries(),active=read(path.join(library,'active.json'));validate(all,active);return {all,active};}
export function syncLibrary(){
  const {all,active}=state(),bases=nativeCatalog(),byId=new Map(all.map(e=>[e.id,e]));
  for(const item of all)if(item.animation!=='coordinated'){
    item.animation='coordinated';
    writeFileSync(path.join(library,'exercises',item.id+'.json'),JSON.stringify(item,null,2)+'\n');
  }
  const quote=s=>JSON.stringify(s).replace(/\$/g,'\\$');
  const copies=active.map(id=>{const e=byId.get(id);return `        base.first { it.id == ${quote(e.motion.id)} }.copy(id = ${quote(e.id)}, name = ${quote(e.name)})`;});
  const kotlin=`// Generated by exercise-library. Do not edit by hand.\npackage com.fit50.app\n\ninternal object LibraryExercises {\n    fun additional(base: List<WorkoutPlanEngine.Ex>): List<WorkoutPlanEngine.Ex> = ${copies.length?'listOf(\n'+copies.join(',\n')+'\n    )':'emptyList()'}\n}\n`;
  writeFileSync(path.join(root,'app/src/main/java/com/fit50/app/LibraryExercises.kt'),kotlin);
  const catalog=[...bases.map(e=>({id:e.id,name:e.name})),...active.map(id=>({id,name:byId.get(id).name}))];
  writeFileSync(path.join(root,'tools/coach/exercise-catalog.json'),JSON.stringify(catalog,null,2)+'\n');
  writeFileSync(path.join(root,'tools/coach/library-motions.json'),JSON.stringify(Object.fromEntries(all.map(e=>[e.id,{...e.motion,name:e.name} ])),null,2)+'\n');
  return {all,active};
}
export function seed(){
  mkdirSync(path.join(library,'exercises'),{recursive:true});
  const source=readFileSync(path.join(root,'tools/coach/full-body.mjs'),'utf8');
  for(const e of nativeCatalog()){
    const item={...e,kind:'base',motion:{id:e.id,speed:1},animation:source.includes(`case '${e.id}'`)?'coordinated':'joint-pose',review:'preview-before-use'};
    writeFileSync(path.join(library,'exercises',e.id+'.json'),JSON.stringify(item,null,2)+'\n');
  }
  const variants=['march','chair_squat','sit_to_stand','wall_push','counter_push','band_row','heel_raise','glute_bridge','dead_bug','bird_dog','chair_knee_lift','seated_leg_extend','chair_row','weight_shift','cat_cow','wall_calf_raise','hip_hinge','good_morning','biceps_band','front_raise','lateral_raise','seated_march','chair_punch','standing_knee_drive'];
  for(const id of variants){const base=read(path.join(library,'exercises',id+'.json'));const item={...base,id:id+'_slow',name:base.name+' — קצב איטי',kind:'tempo-variant',motion:{id,speed:.7}};
    writeFileSync(path.join(library,'exercises',item.id+'.json'),JSON.stringify(item,null,2)+'\n');}
}
if(process.argv.includes('--seed'))seed();
