// Generated by exercise-library. Do not edit by hand.
package com.fit50.app

internal object LibraryExercises {
    fun additional(base: List<WorkoutPlanEngine.Ex>): List<WorkoutPlanEngine.Ex> = emptyList()
}
